# Week 1 Weekend Assignment: Data Science Foundations & Numerical Computing with NumPy

# Overview
This assignment reinforces the concepts covered during Week 1 by combining the Data Science Lifecycle with practical NumPy programming.

You will:

Solve practical NumPy problems using vectorization, broadcasting, slicing, and boolean masking.
Implement a simple signal-processing algorithm using NumPy.

Part 1: NumPy Practical Lab


In [2]:
import numpy as np

In [4]:
np.random.seed(42)
raw_temperatures = np.random.normal(loc=24.0, scale=3.0, size=72)

# overwrite 5 specific hours with unrealistic values, to simulate faulty sensor readings.
raw_temperatures[[5, 12, 28, 45, 60]] = [99.9, -15.0, 88.8, -50.0, 102.4]


In [6]:
raw_temperatures

array([ 25.49014246,  23.5852071 ,  25.94306561,  28.56908957,
        23.29753988,  99.9       ,  28.73763845,  26.30230419,
        22.59157684,  25.62768013,  22.60974692,  22.60281074,
       -15.        ,  18.26015927,  18.8252465 ,  22.31313741,
        20.96150664,  24.942742  ,  21.27592777,  19.7630889 ,
        28.39694631,  23.3226711 ,  24.20258461,  19.72575544,
        22.36685183,  24.33276777,  20.54701927,  25.12709406,
        88.8       ,  23.12491875,  22.19488016,  29.55683455,
        23.95950833,  20.82686721,  26.46763474,  20.33746905,
        24.62659079,  18.12098963,  20.01544185,  24.59058371,
        26.21539974,  24.51410484,  23.65305515,  23.09668891,
        19.56443403, -50.        ,  22.61808369,  27.17136668,
        25.03085487,  18.71087953,  24.97225191,  22.84475316,
        21.969234  ,  25.83502887,  27.09299857,  26.79384036,
        21.48234743,  23.07236287,  24.99379029,  26.92663538,
       102.4       ,  23.44302307,  20.68099508,  20.41

In [7]:
in_range = (raw_temperatures >= 15.0) & (raw_temperatures <= 40.0)


In [8]:
in_range

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
# Counting how many readings passed vs failed the range check.
print("Realistic readings:", in_range.sum())
print("Faulty readings:", (~in_range).sum())


Realistic readings: 67
Faulty readings: 5


In [10]:
# We take the median from ONLY the realistic readings (in_range selects just those).
# Using the median of everything would still be pulled off by the 5 broken values.
fallback_value = np.median(raw_temperatures[in_range])
fallback_value

np.float64(23.65305515283528)

In [11]:
# np.where swaps in the fallback wherever a reading failed the check,
# and leaves every realistic reading untouched.
raw_temperatures = np.where(in_range, raw_temperatures, fallback_value)
raw_temperatures

array([25.49014246, 23.5852071 , 25.94306561, 28.56908957, 23.29753988,
       23.65305515, 28.73763845, 26.30230419, 22.59157684, 25.62768013,
       22.60974692, 22.60281074, 23.65305515, 18.26015927, 18.8252465 ,
       22.31313741, 20.96150664, 24.942742  , 21.27592777, 19.7630889 ,
       28.39694631, 23.3226711 , 24.20258461, 19.72575544, 22.36685183,
       24.33276777, 20.54701927, 25.12709406, 23.65305515, 23.12491875,
       22.19488016, 29.55683455, 23.95950833, 20.82686721, 26.46763474,
       20.33746905, 24.62659079, 18.12098963, 20.01544185, 24.59058371,
       26.21539974, 24.51410484, 23.65305515, 23.09668891, 19.56443403,
       23.65305515, 22.61808369, 27.17136668, 25.03085487, 18.71087953,
       24.97225191, 22.84475316, 21.969234  , 25.83502887, 27.09299857,
       26.79384036, 21.48234743, 23.07236287, 24.99379029, 26.92663538,
       23.65305515, 23.44302307, 20.68099508, 20.41138013, 26.43757747,
       28.06872009, 23.78396964, 27.01059869, 25.08490808, 22.06

In [12]:
print("Mean:", round(np.mean(raw_temperatures), 2))
print("Standard Deviation:", round(np.std(raw_temperatures), 2))
print("Variance:", round(np.var(raw_temperatures), 2))

Mean: 23.74
Standard Deviation: 2.69
Variance: 7.24


# Task 1.2: Matrix Slicing & Strided Operations

In [13]:
# 64 consecutive integers reshaped into an 8x8 grid.
grid = np.arange(10, 74).reshape(8, 8)
grid

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73]])

In [14]:
# Rows/columns 2,3,4,5 are the 4 middle ones out of 0-7,
# so the slice starts at 2 and stops just before 6.
center_block = grid[2:6, 2:6]
center_block

array([[28, 29, 30, 31],
       [36, 37, 38, 39],
       [44, 45, 46, 47],
       [52, 53, 54, 55]])

In [15]:
last_column = grid[:, -1]
last_column

array([17, 25, 33, 41, 49, 57, 65, 73])

In [16]:
downsampled = grid[::2, ::2]
downsampled

array([[10, 12, 14, 16],
       [26, 28, 30, 32],
       [42, 44, 46, 48],
       [58, 60, 62, 64]])

# Part 2: Sliding Median Filter

In [17]:
# short signal with two obvious spikes: 99 and -45.
signal = np.array([10, 11, 99, 12, 13, -45, 14, 15, 16])
signal


array([ 10,  11,  99,  12,  13, -45,  14,  15,  16])

In [18]:
filtered_signal = signal.copy()
filtered_signal


array([ 10,  11,  99,  12,  13, -45,  14,  15,  16])

In [19]:
# Index 0 and the last index don't have a neighbour on both sides,
# so we only slide the window across positions 1 through 7.
for position in range(1, len(signal) - 1):
    neighbourhood = signal[position - 1 : position + 2]   # the value plus one neighbour on each side
    filtered_signal[position] = np.median(neighbourhood)   # the middle-ranked value replaces the centre

print("Original signal:", signal)
print("Filtered signal:", filtered_signal)


Original signal: [ 10  11  99  12  13 -45  14  15  16]
Filtered signal: [10 11 12 13 12 13 14 15 16]
